# Generated by Django 2.2.3 on 2020-06-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='created_at',
            new_name='accepted_at',
        ),
    ]
