# Generated by Django 2.2.3 on 2020-06-02 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cers', '0002_auto_20200602_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='student_number',
            new_name='number',
        ),
    ]
