# Generated by Django 2.2.3 on 2020-06-02 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cers', '0003_auto_20200602_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='is_entry',
            new_name='is_in',
        ),
    ]
